services:
  - appName: myfirstapp
    port: 3333
    configmap:
      name: myfirstapp-configmap-v1
      data:
        CUSTOM_HEADER: 'This is first app!'
        BG_COLOR: '#1abe93'
        FONT_COLOR: '#be1a1a'
    image:
      name: devopsjourney1/mywebapp
      tag: latest

  # - appName: mysecondapp
  #   replicas: 3
  #   port: 4444
  #   configmap:
  #     name: mysecondapp-configmap-v1
  #     data:
  #       CUSTOM_HEADER: 'This is second app!'
  #       BG_COLOR: '#1abe93'
  #       FONT_COLOR: '#be1a1a'
  #   image:
  #     name: devopsjourney1/mywebapp
  #     tag: latest
    
