{{- range $key, $value := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.appName }}
  labels:
    app: {{ $value.appName }}
spec:
  replicas: {{ $value.replicas }}
  selector:
    matchLabels:
      app: {{ $value.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ $value.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ $value.image.name }}:{{ $value.image.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ $value.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
{{- end }}