{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.appName }}
  labels:
    app: {{ $value.appName }}
spec:
  ports:
  - port: {{ $value.port }}
    protocol: TCP
    name: {{ $value.appName }}
  selector:
    app: {{ $value.appName }}
    tier: frontend
  type: NodePort
{{- end }}
