{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.appName }}
  labels:
    app: {{ $value.appName }}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: {{ $value.appName }}
    tier: frontend
  type: LoadBalancer
{{- end }}
